export const products = [
  {
    id: 1,
    title: "Arandanos",
    price: 1400,
    stock: 10,
    description: "Arandanos congelados IQF grado A",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2021/08/5a38d9eb9549c0.6676784215136752436115-150x150.png",
  },
  {
    id: 2,
    title: "Frutillas",
    price: 1300,
    stock: 10,
    description: "Frutillas congeladas IQF grado A",
    category: "Frutas",
    img: "https://olacongelados.com/wp-content/uploads/2021/08/pngegg-13-150x150.png",
  },
  {
    id: 3,
    title: "Mango",
    price: 1500,
    stock: 10,
    description: "Mango congelados IQF cubeteado",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-5-150x150.png",
  },
  {
    id: 4,
    title: "Durazno",
    price: 1500,
    stock: 10,
    description: "Durazno congelado IQF cubeteado",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-11-150x150.png",
  },
  {
    id: 5,
    title: "Mix berries sin frutillas",
    price: 2200,
    stock: 10,
    description: "Arandanos, Moras y Frambuesas",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-12-150x150.png",
  },
  {
    id: 6,
    title: "Mix berries con frutillas",
    price: 2000,
    stock: 10,
    description: "Arandanos, Moras, Frambuesas y frutillas",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngwing.com_-150x150.png",
  },
];
