export const products = [
  {
    id: 1,
    title: "Arandanos seleccion",
    price: 1040,
    stock: 10,
    description: "Arandanos congelados IQF grado A",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2021/08/5a38d9eb9549c0.6676784215136752436115-150x150.png",
  },
  {
    id: 2,
    title: "Frutillas seleccion",
    price: 860,
    stock: 10,
    description: "Frutillas congeladas IQF grado A",
    category: "Frutas",
    img: "https://olacongelados.com/wp-content/uploads/2021/08/pngegg-13-150x150.png",
  },
  {
    id: 3,
    title: "Mango en cubo",
    price: 1420,
    stock: 10,
    description: "Mango congelados IQF cubeteado",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-5-150x150.png",
  },
  {
    id: 4,
    title: "Durazno en cubos",
    price: 1390,
    stock: 10,
    description: "Durazno congelado IQF cubeteado",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-11-150x150.png",
  },
  {
    id: 5,
    title: "Berries s/frutillas",
    price: 1990,
    stock: 10,
    description: "Arandanos, Moras y Frambuesas",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-12-150x150.png",
  },
  {
    id: 6,
    title: "Berries c/frutillas",
    price: 1720,
    stock: 10,
    description: "Arandanos, Moras, Frambuesas y frutillas",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngwing.com_-150x150.png",
  },
  {
    id: 7,
    title: "Frambuesas enteras ",
    price: 3570,
    stock: 10,
    description: "Frambuesa IQF grado A",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-1-150x150.png",
  },
  {
    id: 8,
    title: "Moras enteras",
    price: 2190,
    stock: 10,
    description: "Moras IQF grado A",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-2-150x150.png",
  },
  {
    id: 9,
    title: "Maracuya c/semillas",
    price: 2150,
    stock: 10,
    description: "Pulpa 100% maracuya con semillas",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-3-150x150.png",
  },
  {
    id: 10,
    title: "Maracuya s/semillas",
    price: 2000,
    stock: 10,
    description: "Pulpa 100% maracuya sin semillas",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-3-150x150.png",
  },
  {
    id: 11,
    title: "Anana en cubos",
    price: 1540,
    stock: 10,
    description: "Anana en cubos IQF",
    category: "frutas",
    img: "https://t2.gstatic.com/licensed-image?q=tbn:ANd9GcRtI5JE5ZTZopReolaQYf3SHj1PFi9c3y_T3RPxEonQBYtciBdI2R7t-WfIhM43QH5O",
  },
  {
    id: 12,
    title: "Papaya en cubos",
    price: 1430,
    stock: 10,
    description: "Papaya en cubos IQF",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-8-150x150.png",
  },
  {
    id: 13,
    title: "Açai pulpa con guarana  ",
    price: 2180,
    stock: 10,
    description: "Pulpa de Açai con guarana listo para consumir",
    category: "frutas",
    img: "https://olacongelados.com/wp-content/uploads/2023/02/1-final-min-scaled-e1679179350586-150x150.webp",
  },
  {
    id: 14,
    title: "Espinaca",
    price: 660,
    stock: 10,
    description: "Espinaca IQF",
    category: "verduras",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-14-150x150.png",
  },
  {
    id: 15,
    title: "Acelga",
    price: 650,
    stock: 10,
    description: "Acelga IQF",
    category: "verduras",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-15-150x150.png",
  },
  {
    id: 16,
    title: "Brocoli",
    price: 780,
    stock: 10,
    description: "Brocoli florete IQF",
    category: "verduras",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-16-150x150.png",
  },
  {
    id: 17,
    title: "Choclo",
    price: 980,
    stock: 10,
    description: "choclo en granos IQF",
    category: "verduras",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-17-150x150.png",
  },
  {
    id: 18,
    title: "Arvejas",
    price: 800,
    stock: 10,
    description: "Arvejas IQF",
    category: "verduras",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-18-150x150.png",
  },
  {
    id: 19,
    title: "Mix primavera",
    price: 800,
    stock: 10,
    description: "Mix de arveja, choclo y zanahoria",
    category: "verduras",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-19-150x150.png",
  },
  {
    id: 20,
    title: "Zapallo",
    price: 610,
    stock: 10,
    description: "zapallo en cubos IQF",
    category: "verduras",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-20-150x150.png",
  },
  {
    id: 21,
    title: "Zanahoria",
    price: 690,
    stock: 10,
    description: "zanahoria en cubos IQF",
    category: "verduras",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-21-150x150.png",
  },
  {
    id: 22,
    title: "Morron",
    price: 1120,
    stock: 10,
    description: "morron cubeteado IQF",
    category: "verduras",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-23-150x150.png",
  },
  {
    id: 23,
    title: "Morron tricolor",
    price: 1120,
    stock: 10,
    description: "Mix morron verde, rojo y amarillo",
    category: "verduras",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-22-150x150.png",
  },
  {
    id: 24,
    title: "cebolla",
    price: 970,
    stock: 10,
    description: " cebolla en cubos IQF",
    category: "verduras",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/pngegg-24-150x150.png",
  },
  {
    id: 25,
    title: "Mix vegetales",
    price: 990,
    stock: 10,
    description: "Mix de cebolla y morron tricolor",
    category: "verduras",
    img: "https://olacongelados.com/wp-content/uploads/2023/04/potatoes-jacket-potatoes-meal-1635401-150x150.jpg",
  },
];
